'use client'
// app/admin/analytics/page.tsx — Chance Analytics Dashboard v1.2
// v1.2: Colourful charts, clean Y-axis rounding, bigger fonts, world map tab, vibrant
import { useState, useEffect, useMemo } from 'react'

var FONT = "-apple-system, BlinkMacSystemFont, 'SF Pro Display', 'SF Pro Text', 'Helvetica Neue', sans-serif"
var PLAT = '#A8B2BD'; var PLAT_DIM = '#828D98'; var PLAT_DARK = '#6b7580'; var GOLD = '#d4af37'; var BG = '#07070c'
var CARD_BG = 'rgba(255,255,255,0.04)'; var CARD_BORDER = 'rgba(255,255,255,0.08)'
var GREEN = '#34d399'; var RED = '#f87171'; var BLUE = '#60a5fa'; var PURPLE = '#a78bfa'; var AMBER = '#fbbf24'
var TZ_COORDS: Record<string, [number, number]> = {
  'America/New_York': [40.7, -74], 'America/Chicago': [41.9, -87.6], 'America/Denver': [39.7, -105], 'America/Los_Angeles': [34, -118.2], 'America/Toronto': [43.7, -79.4], 'America/Vancouver': [49.3, -123.1], 'America/Sao_Paulo': [-23.5, -46.6], 'America/Mexico_City': [19.4, -99.1], 'America/Buenos_Aires': [-34.6, -58.4], 'America/Bogota': [4.6, -74.1],
  'Europe/London': [51.5, -0.1], 'Europe/Paris': [48.9, 2.3], 'Europe/Berlin': [52.5, 13.4], 'Europe/Madrid': [40.4, -3.7], 'Europe/Rome': [41.9, 12.5], 'Europe/Amsterdam': [52.4, 4.9], 'Europe/Stockholm': [59.3, 18.1], 'Europe/Dublin': [53.3, -6.3], 'Europe/Lisbon': [38.7, -9.1], 'Europe/Warsaw': [52.2, 21],
  'Asia/Tokyo': [35.7, 139.7], 'Asia/Shanghai': [31.2, 121.5], 'Asia/Singapore': [1.3, 103.8], 'Asia/Dubai': [25.2, 55.3], 'Asia/Kolkata': [19, 72.9], 'Asia/Seoul': [37.6, 127], 'Asia/Hong_Kong': [22.3, 114.2], 'Asia/Bangkok': [13.8, 100.5], 'Asia/Jakarta': [-6.2, 106.8],
  'Australia/Sydney': [-33.9, 151.2], 'Australia/Melbourne': [-37.8, 145], 'Pacific/Auckland': [-36.8, 174.8],
  'Africa/Johannesburg': [-26.2, 28], 'Africa/Lagos': [6.5, 3.4], 'Africa/Cairo': [30, 31.2], 'Africa/Nairobi': [-1.3, 36.8],
}
function tzToCoords(tz: string): [number, number] | null { return TZ_COORDS[tz] || null }
function latLngToXY(lat: number, lng: number, w: number, h: number): [number, number] { var x = (lng + 180) / 360 * w; var latRad = lat * Math.PI / 180; var mercN = Math.log(Math.tan(Math.PI / 4 + latRad / 2)); var y = h / 2 - (mercN / Math.PI) * (h / 2); return [x, y] }
function fmtNum(n: number): string { if (n >= 1000000) return (n / 1000000).toFixed(1) + 'M'; if (n >= 1000) return (n / 1000).toFixed(1) + 'K'; return n.toLocaleString() }
function fmtCat(cat: string): string { if (cat === 'ai') return 'AI'; return cat.split(/[-/]/).map(function (w) { return w.charAt(0).toUpperCase() + w.slice(1) }).join(' / ') }
function fmtDate(d: string): string { var p = d.split('-'); return p[1] + '/' + p[2] }
// Clean Y-axis: round max up to nearest nice number (10, 20, 50, 100, etc.)
function niceMax(val: number): number { if (val <= 0) return 10; var mag = Math.pow(10, Math.floor(Math.log10(val))); var norm = val / mag; if (norm <= 1) return mag; if (norm <= 2) return 2 * mag; if (norm <= 5) return 5 * mag; return 10 * mag }

function SvgLineChart({ data, lines, width, height }: { data: any[]; lines: { key: string; color: string; label: string }[]; width: number; height: number }) {
  if (!data || data.length === 0) return <div style={{ height: height, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '13px', color: PLAT_DARK }}>No data yet</div>
  var pad = { t: 10, r: 10, b: 28, l: 40 }; var cw = width - pad.l - pad.r; var ch = height - pad.t - pad.b
  var allVals: number[] = []; lines.forEach(function (l) { data.forEach(function (d) { allVals.push(d[l.key] || 0) }) })
  var rawMax = Math.max(1, ...allVals); var nMax = niceMax(rawMax); var steps = 4; var stepSize = niceMax(Math.ceil(nMax / steps)); var maxVal = stepSize * steps
  function toX(i: number) { return pad.l + (i / Math.max(1, data.length - 1)) * cw }
  function toY(v: number) { return pad.t + ch - (v / maxVal) * ch }
  var xLabels = data.length <= 8 ? data.map(function (_, i) { return i }) : data.map(function (_, i) { return i }).filter(function (i) { return i % Math.ceil(data.length / 6) === 0 })
  return (<svg width={width} height={height} viewBox={'0 0 ' + width + ' ' + height} style={{ width: '100%', height: 'auto' }}>
    {[0, 1, 2, 3, 4].map(function (s) { var val = s * stepSize; var y = toY(val); return <g key={s}><line x1={pad.l} y1={y} x2={width - pad.r} y2={y} stroke="rgba(255,255,255,0.05)" strokeWidth={0.5} /><text x={pad.l - 6} y={y + 3} fill={PLAT_DARK} fontSize={10} fontWeight={600} textAnchor="end">{Math.round(val)}</text></g> })}
    {xLabels.map(function (i) { return <text key={i} x={toX(i)} y={height - 6} fill={PLAT_DARK} fontSize={9} fontWeight={600} textAnchor="middle">{data[i].date || ''}</text> })}
    {lines.map(function (line) { var pts = data.map(function (d, i) { return toX(i) + ',' + toY(d[line.key] || 0) }).join(' '); return <polyline key={line.key} points={pts} fill="none" stroke={line.color} strokeWidth={2} strokeLinejoin="round" strokeLinecap="round" /> })}
  </svg>)
}
function SvgBarChart({ data, dataKey, width, height, color, gradientTo }: { data: any[]; dataKey: string; width: number; height: number; color: string; gradientTo?: string }) {
  if (!data || data.length === 0) return <div style={{ height: height, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '13px', color: PLAT_DARK }}>No data yet</div>
  var pad = { t: 10, r: 10, b: 28, l: 36 }; var cw = width - pad.l - pad.r; var ch = height - pad.t - pad.b
  var rawMax = Math.max(1, ...data.map(function (d) { return d[dataKey] || 0 })); var nMax = niceMax(rawMax); var steps = 4; var stepSize = niceMax(Math.ceil(nMax / steps)); var maxVal = stepSize * steps; var barW = Math.max(3, (cw / data.length) - 3)
  var xLabels = data.length <= 8 ? data.map(function (_, i) { return i }) : data.map(function (_, i) { return i }).filter(function (i) { return i % Math.ceil(data.length / 6) === 0 })
  var gId = 'bg' + Math.random().toString(36).slice(2, 8)
  return (<svg width={width} height={height} viewBox={'0 0 ' + width + ' ' + height} style={{ width: '100%', height: 'auto' }}>
    {gradientTo && <defs><linearGradient id={gId} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={color} /><stop offset="100%" stopColor={gradientTo} /></linearGradient></defs>}
    {[0, 1, 2, 3, 4].map(function (s) { var val = s * stepSize; var y = pad.t + ch - (val / maxVal) * ch; return <g key={s}><line x1={pad.l} y1={y} x2={width - pad.r} y2={y} stroke="rgba(255,255,255,0.05)" strokeWidth={0.5} /><text x={pad.l - 6} y={y + 3} fill={PLAT_DARK} fontSize={10} fontWeight={600} textAnchor="end">{Math.round(val)}</text></g> })}
    {data.map(function (d, i) { var x = pad.l + (i / data.length) * cw + 1; var val = d[dataKey] || 0; var barH = Math.max(1, (val / maxVal) * ch); return <rect key={i} x={x} y={pad.t + ch - barH} width={barW} height={barH} fill={gradientTo ? 'url(#' + gId + ')' : color} rx={2} opacity={0.85} /> })}
    {xLabels.map(function (i) { return <text key={i} x={pad.l + (i / data.length) * cw + barW / 2} y={height - 6} fill={PLAT_DARK} fontSize={9} fontWeight={600} textAnchor="middle">{data[i].date || ''}</text> })}
  </svg>)
}
function SvgDonut({ segments, size, label }: { segments: { value: number; color: string; label: string }[]; size: number; label: string }) {
  var total = segments.reduce(function (s, seg) { return s + seg.value }, 0)
  if (total === 0) return <div style={{ width: size, height: size, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '13px', color: PLAT_DARK }}>No data</div>
  var cx = size / 2; var cy = size / 2; var r = size * 0.35; var strokeW = size * 0.12; var circumference = 2 * Math.PI * r; var offset = 0
  return (<svg width={size} height={size} viewBox={'0 0 ' + size + ' ' + size}>{segments.map(function (seg, i) { var segLen = (seg.value / total) * circumference; var gap = 4; var el = <circle key={i} cx={cx} cy={cy} r={r} fill="none" stroke={seg.color} strokeWidth={strokeW} strokeDasharray={Math.max(0, segLen - gap) + ' ' + (circumference - segLen + gap)} strokeDashoffset={-offset} strokeLinecap="round" transform={'rotate(-90 ' + cx + ' ' + cy + ')'} />; offset += segLen; return el })}<text x={cx} y={cy - 4} fill="#e0e4e8" fontSize={size * 0.14} fontWeight={800} textAnchor="middle">{fmtNum(total)}</text><text x={cx} y={cy + size * 0.09} fill={PLAT_DIM} fontSize={size * 0.07} fontWeight={600} textAnchor="middle">{label}</text></svg>)
}
function StatCard({ label, value, sub, color, delay }: { label: string; value: string; sub?: string; color?: string; delay?: number }) {
  return (<div style={{ background: CARD_BG, border: '1px solid ' + CARD_BORDER, borderRadius: '12px', padding: '12px 16px', display: 'flex', flexDirection: 'column', gap: '2px', animation: 'analyticsCardIn 0.4s ease-out ' + (delay || 0) + 'ms both' }}><div style={{ fontSize: '10px', fontWeight: 700, color: PLAT_DIM, textTransform: 'uppercase', letterSpacing: '1.5px' }}>{label}</div><div style={{ fontSize: '24px', fontWeight: 800, color: color || '#e0e4e8', letterSpacing: '-0.5px' }}>{value}</div>{sub && <div style={{ fontSize: '11px', color: PLAT_DARK, fontWeight: 600 }}>{sub}</div>}</div>)
}
function SectionHeader({ title }: { title: string }) {
  return (<div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '16px', marginTop: '36px' }}><div style={{ height: '1px', flex: 1, background: 'linear-gradient(90deg, transparent, rgba(255,255,255,0.08))' }} /><span style={{ fontSize: '13px', fontWeight: 700, letterSpacing: '2px', textTransform: 'uppercase', color: PLAT_DIM }}>{title}</span><div style={{ height: '1px', flex: 1, background: 'linear-gradient(90deg, rgba(255,255,255,0.08), transparent)' }} /></div>)
}

var preClickAdmin: HTMLAudioElement | null = null
if (typeof window !== 'undefined') { preClickAdmin = new Audio('/sounds/click.mp3'); preClickAdmin.preload = 'auto'; preClickAdmin.volume = 0.7 }
function playClickAdmin() { if (!preClickAdmin) return; try { var c = preClickAdmin.cloneNode(true) as HTMLAudioElement; c.volume = 0.7; c.play().catch(function () {}) } catch (e) {} }

export default function AnalyticsPage() {
  var [authed, setAuthed] = useState(false); var [checkingAuth, setCheckingAuth] = useState(true); var [pw, setPw] = useState(''); var [pwError, setPwError] = useState(false)
  var [data, setData] = useState<any>(null); var [loading, setLoading] = useState(true); var [error, setError] = useState<string | null>(null)
  var [activityTab, setActivityTab] = useState<'dau' | 'map'>('dau')
  useEffect(function () { fetch('/api/admin/me', { credentials: 'include' }).then(function (r) { return r.json() }).then(function (j) { if (j?.ok) setAuthed(true) }).catch(function () {}).finally(function () { setCheckingAuth(false) }) }, [])
  useEffect(function () { if (!authed) return; setLoading(true); fetch('/api/admin/analytics', { credentials: 'include' }).then(function (r) { return r.json() }).then(function (d) { if (d.ok) { setData(d); setError(null) } else { setError(d.error || 'Failed') } }).catch(function (e) { setError(e.message) }).finally(function () { setLoading(false) }) }, [authed])
  function handleLogin() { fetch('/api/admin/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ password: pw }), credentials: 'include' }).then(function (r) { return r.json() }).then(function (j) { if (j?.ok) { setAuthed(true); setPwError(false) } else { setPwError(true) } }).catch(function () { setPwError(true) }) }
  var reactionChartData = useMemo(function () { if (!data?.reactionTimeline) return []; var days: Record<string, any> = {}; for (var i = 0; i < data.reactionTimeline.length; i++) { var r = data.reactionTimeline[i]; var day = r.created_at.split('T')[0]; if (!days[day]) days[day] = { date: day, mindblown: 0, neutral: 0, yawn: 0 }; if (r.event_type === 'mindblown') days[day].mindblown++; else if (r.event_type === 'neutral') days[day].neutral++; else if (r.event_type === 'yawn') days[day].yawn++ }; return Object.values(days).sort(function (a: any, b: any) { return a.date.localeCompare(b.date) }).map(function (d: any) { return { date: fmtDate(d.date), mindblown: d.mindblown, neutral: d.neutral, yawn: d.yawn } }) }, [data])
  var dauChartData = useMemo(function () { if (!data?.dauData) return []; var days: Record<string, Set<string>> = {}; for (var i = 0; i < data.dauData.length; i++) { var d = data.dauData[i]; var day = d.created_at.split('T')[0]; if (!days[day]) days[day] = new Set(); days[day].add(d.session_id) }; return Object.entries(days).sort(function (a, b) { return a[0].localeCompare(b[0]) }).map(function (e) { return { date: fmtDate(e[0]), users: e[1].size } }) }, [data])
  var heatmapGrid = useMemo(function () { if (!data?.heatmapData) return []; var days: Record<string, number> = {}; for (var i = 0; i < data.heatmapData.length; i++) { var day = data.heatmapData[i].created_at.split('T')[0]; days[day] = (days[day] || 0) + 1 }; var maxCount = Math.max(1, ...Object.values(days)); var grid = []; var now = new Date(); for (var d = 89; d >= 0; d--) { var date = new Date(now); date.setDate(date.getDate() - d); var key = date.toISOString().split('T')[0]; var count = days[key] || 0; grid.push({ date: key, count: count, intensity: count / maxCount }) }; return grid }, [data])
  var mapDots = useMemo(function () { if (!data?.timezones) return []; var tzCounts: Record<string, number> = {}; for (var i = 0; i < data.timezones.length; i++) { var tz = data.timezones[i].timezone; if (tz) tzCounts[tz] = (tzCounts[tz] || 0) + 1 }; var dots = []; for (var tzKey in tzCounts) { var coords = tzToCoords(tzKey); if (coords) dots.push({ tz: tzKey, lat: coords[0], lng: coords[1], count: tzCounts[tzKey] }) }; return dots }, [data])

  if (checkingAuth) return <div style={{ minHeight: '100vh', background: BG }} />
  if (!authed) return (<div style={{ minHeight: '100vh', background: BG, color: PLAT, fontFamily: FONT, display: 'flex', alignItems: 'center', justifyContent: 'center' }}><div style={{ textAlign: 'center', maxWidth: '320px', width: '100%', padding: '0 24px' }}><img src="/logo-c.png" alt="Chance" style={{ width: '48px', height: '48px', margin: '0 auto 16px', display: 'block', opacity: 0.5 }} /><h1 style={{ fontSize: '22px', fontWeight: 800, letterSpacing: '3px', textTransform: 'uppercase', marginBottom: '24px', color: '#e0e4e8' }}>Analytics</h1><input type="password" style={{ width: '100%', padding: '12px 14px', borderRadius: '12px', background: 'rgba(255,255,255,0.06)', border: '1px solid rgba(255,255,255,0.1)', color: PLAT, fontSize: '15px', fontFamily: FONT, textAlign: 'center', letterSpacing: '2px', marginBottom: '14px', outline: 'none', boxSizing: 'border-box' }} placeholder="Admin password" value={pw} onChange={function (e) { setPw(e.target.value); setPwError(false) }} onKeyDown={function (e) { if (e.key === 'Enter') handleLogin() }} autoFocus />{pwError && <p style={{ color: RED, fontSize: '13px', marginBottom: '8px' }}>Wrong password</p>}<button onClick={handleLogin} style={{ padding: '10px 28px', borderRadius: '12px', background: 'rgba(255,255,255,0.08)', border: '1px solid rgba(255,255,255,0.12)', color: '#e0e4e8', fontSize: '13px', fontWeight: 700, fontFamily: FONT, cursor: 'pointer', letterSpacing: '1px', textTransform: 'uppercase' }}>Enter</button></div></div>)
  if (loading) return (<div style={{ minHeight: '100vh', background: BG, color: PLAT, fontFamily: FONT, display: 'flex', alignItems: 'center', justifyContent: 'center' }}><div style={{ textAlign: 'center' }}><img src="/logo-c.png" alt="" style={{ width: '48px', height: '48px', opacity: 0.4, margin: '0 auto 16px', display: 'block' }} /><p style={{ fontSize: '14px', color: PLAT_DIM }}>Loading analytics...</p></div></div>)
  if (error) return (<div style={{ minHeight: '100vh', background: BG, color: RED, fontFamily: FONT, display: 'flex', alignItems: 'center', justifyContent: 'center' }}><p style={{ fontSize: '15px' }}>Error: {error}</p></div>)

  var hero = data?.hero || {}; var sentiment = data?.sentiment || {}; var urlHealth = data?.urlHealth || {}; var poolExhaustion = data?.poolExhaustion || {}
  var totalReactions = (sentiment.mindblown || 0) + (sentiment.neutral || 0) + (sentiment.yawn || 0)
  var sentimentBar = totalReactions > 0 ? { m: sentiment.mindblown / totalReactions * 100, n: sentiment.neutral / totalReactions * 100, y: sentiment.yawn / totalReactions * 100 } : { m: 33, n: 34, y: 33 }
  var daysLeft = poolExhaustion.totalPool > 0 && poolExhaustion.dailyBurnRate > 0 ? Math.round((poolExhaustion.totalPool - poolExhaustion.totalSeen) / poolExhaustion.dailyBurnRate) : null
  var tabStyle = function (active: boolean) { return { padding: '8px 20px', borderRadius: '10px', border: '1px solid ' + (active ? 'rgba(168,178,189,0.3)' : CARD_BORDER), background: active ? 'rgba(168,178,189,0.1)' : CARD_BG, color: active ? '#e0e4e8' : PLAT_DARK, fontSize: '13px', fontWeight: 700 as const, fontFamily: FONT, cursor: 'pointer' as const, outline: 'none' as const, transition: 'all 0.15s ease' } }

  return (
    <div style={{ minHeight: '100vh', background: BG, color: PLAT, fontFamily: FONT }}>
      <style>{`@keyframes analyticsCardIn { from { opacity: 0; transform: translateY(6px); } to { opacity: 1; transform: translateY(0); } } @keyframes analyticsPulse { 0%,100% { opacity: 1; } 50% { opacity: 0.4; } } .ag4 { display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px; } .ag2 { display: grid; grid-template-columns: 3fr 2fr; gap: 16px; } .ag2e { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; } @media (max-width: 768px) { .ag4 { grid-template-columns: repeat(2, 1fr); } .ag2, .ag2e { grid-template-columns: 1fr; } }`}</style>
      <div style={{ maxWidth: '1100px', margin: '0 auto', padding: '28px 24px 60px' }}>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '36px' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '14px' }}><img src="/logo-c.png" alt="Chance" style={{ width: '36px', height: '36px', opacity: 0.7 }} /><h1 style={{ fontSize: '26px', fontWeight: 800, color: '#e0e4e8', letterSpacing: '4px', textTransform: 'uppercase', margin: 0 }}>Analytics</h1><div style={{ width: '10px', height: '10px', borderRadius: '50%', background: GREEN, animation: 'analyticsPulse 2s ease-in-out infinite', marginLeft: '4px' }} /></div>
          <a href="/admin" onClick={function () { playClickAdmin() }} style={{ fontSize: '13px', color: PLAT_DIM, textDecoration: 'none', padding: '8px 16px', borderRadius: '10px', border: '1px solid ' + CARD_BORDER, background: CARD_BG, fontWeight: 600, transition: 'all 0.15s ease' }} onMouseOver={function (e) { (e.currentTarget as HTMLElement).style.background = 'rgba(255,255,255,0.08)'; (e.currentTarget as HTMLElement).style.transform = 'scale(1.03)' }} onMouseOut={function (e) { (e.currentTarget as HTMLElement).style.background = CARD_BG; (e.currentTarget as HTMLElement).style.transform = 'scale(1)' }}>&#8592; Admin</a>
        </div>
        <div className="ag4"><StatCard label="Revenue" value="$0" sub="Coming Soon" color={GOLD} delay={0} /><StatCard label="Live URLs" value={fmtNum(hero.liveUrls || 0)} sub={fmtNum(hero.deadUrls || 0) + ' dead'} delay={50} /><StatCard label="Users" value={String(hero.totalUsers || 0)} sub={(hero.authUsers || 0) + ' signed up'} delay={100} /><StatCard label="Gold Minted" value={fmtNum(hero.totalGold || 0)} sub={fmtNum(hero.totalEvents || 0) + ' events'} color={GOLD} delay={150} /></div>
        <div className="ag4" style={{ marginTop: '10px' }}><StatCard label="Reactions Today" value={String(hero.reactionsToday || 0)} color={GREEN} delay={200} /><StatCard label="Total Reactions" value={fmtNum(totalReactions)} delay={250} /><StatCard label="Pool Runway" value={daysLeft ? daysLeft + ' days' : '\u2014'} sub="Per top user" delay={300} /><StatCard label="Content Quality" value={totalReactions > 0 ? Math.round(sentimentBar.m) + '%' : '\u2014'} sub="Mindblown rate" color={sentimentBar.m > 50 ? GREEN : sentimentBar.m > 30 ? PLAT : RED} delay={350} /></div>
        <SectionHeader title="Reaction Sentiment" />
        <div style={{ background: CARD_BG, border: '1px solid ' + CARD_BORDER, borderRadius: '16px', padding: '18px', animation: 'analyticsCardIn 0.4s ease-out 0.1s both' }}><div style={{ display: 'flex', borderRadius: '10px', overflow: 'hidden', height: '36px' }}><div style={{ width: sentimentBar.m + '%', background: GREEN, transition: 'width 0.5s ease' }} /><div style={{ width: sentimentBar.n + '%', background: BLUE, transition: 'width 0.5s ease' }} /><div style={{ width: sentimentBar.y + '%', background: RED, opacity: 0.7, transition: 'width 0.5s ease' }} /></div><div style={{ display: 'flex', justifyContent: 'space-between', marginTop: '12px', fontSize: '13px', fontWeight: 700 }}><span style={{ color: GREEN }}>Mindblown {Math.round(sentimentBar.m)}%</span><span style={{ color: BLUE }}>Neutral {Math.round(sentimentBar.n)}%</span><span style={{ color: RED }}>Yawn {Math.round(sentimentBar.y)}%</span></div></div>
        <SectionHeader title="Engagement" />
        <div className="ag2">
          <div style={{ background: CARD_BG, border: '1px solid ' + CARD_BORDER, borderRadius: '16px', padding: '18px', animation: 'analyticsCardIn 0.4s ease-out 0.15s both' }}><div style={{ fontSize: '15px', fontWeight: 700, color: '#e0e4e8', marginBottom: '14px' }}>Reactions Over Time</div><div style={{ display: 'flex', gap: '16px', marginBottom: '10px', fontSize: '11px', fontWeight: 700 }}><span style={{ color: GREEN }}>&#9679; Mindblown</span><span style={{ color: BLUE }}>&#9679; Neutral</span><span style={{ color: RED }}>&#9679; Yawn</span></div><SvgLineChart data={reactionChartData} lines={[{ key: 'mindblown', color: GREEN, label: 'Mindblown' }, { key: 'neutral', color: BLUE, label: 'Neutral' }, { key: 'yawn', color: RED, label: 'Yawn' }]} width={500} height={180} /></div>
          <div style={{ background: CARD_BG, border: '1px solid ' + CARD_BORDER, borderRadius: '16px', padding: '18px', animation: 'analyticsCardIn 0.4s ease-out 0.2s both', display: 'flex', flexDirection: 'column', alignItems: 'center' }}><div style={{ fontSize: '15px', fontWeight: 700, color: '#e0e4e8', marginBottom: '14px', alignSelf: 'flex-start' }}>URL Health</div><SvgDonut segments={[{ value: urlHealth.embeddable || 0, color: GREEN, label: 'Embed' }, { value: urlHealth.nonEmbeddable || 0, color: AMBER, label: 'Blocked' }, { value: urlHealth.dead || 0, color: RED, label: 'Dead' }]} size={180} label="URLs" /><div style={{ display: 'flex', gap: '16px', marginTop: '14px', fontSize: '12px', fontWeight: 700 }}><span style={{ display: 'flex', alignItems: 'center', gap: '5px' }}><span style={{ width: '10px', height: '10px', borderRadius: '50%', background: GREEN, display: 'inline-block' }} />Embed</span><span style={{ display: 'flex', alignItems: 'center', gap: '5px' }}><span style={{ width: '10px', height: '10px', borderRadius: '50%', background: AMBER, display: 'inline-block' }} />Blocked</span><span style={{ display: 'flex', alignItems: 'center', gap: '5px' }}><span style={{ width: '10px', height: '10px', borderRadius: '50%', background: RED, display: 'inline-block' }} />Dead</span></div></div>
        </div>
        <SectionHeader title="Activity" />
        <div style={{ display: 'flex', gap: '8px', marginBottom: '16px' }}><button onClick={function () { playClickAdmin(); setActivityTab('dau') }} style={Object.assign({}, tabStyle(activityTab === 'dau'), { WebkitTapHighlightColor: 'transparent', touchAction: 'manipulation' } as any)} onMouseOver={function (e) { (e.currentTarget as HTMLElement).style.transform = 'scale(1.03)' }} onMouseOut={function (e) { (e.currentTarget as HTMLElement).style.transform = 'scale(1)' }}>Daily Active Users</button><button onClick={function () { playClickAdmin(); setActivityTab('map') }} style={Object.assign({}, tabStyle(activityTab === 'map'), { WebkitTapHighlightColor: 'transparent', touchAction: 'manipulation' } as any)} onMouseOver={function (e) { (e.currentTarget as HTMLElement).style.transform = 'scale(1.03)' }} onMouseOut={function (e) { (e.currentTarget as HTMLElement).style.transform = 'scale(1)' }}>World Map</button></div>
        {activityTab === 'dau' && (<div style={{ background: CARD_BG, border: '1px solid ' + CARD_BORDER, borderRadius: '16px', padding: '18px', animation: 'analyticsCardIn 0.3s ease-out both' }}><div style={{ fontSize: '15px', fontWeight: 700, color: '#e0e4e8', marginBottom: '14px' }}>Daily Active Users</div><SvgBarChart data={dauChartData} dataKey="users" width={700} height={160} color={BLUE} gradientTo={GREEN} /></div>)}
        {activityTab === 'map' && (<div style={{ background: CARD_BG, border: '1px solid ' + CARD_BORDER, borderRadius: '16px', padding: '18px', animation: 'analyticsCardIn 0.3s ease-out both' }}><div style={{ fontSize: '15px', fontWeight: 700, color: '#e0e4e8', marginBottom: '14px' }}>User Locations</div>{mapDots.length === 0 ? (<div style={{ textAlign: 'center', padding: '40px 0' }}><p style={{ fontSize: '14px', color: PLAT_DARK }}>No timezone data yet — collecting from sessions</p></div>) : (<div style={{ position: 'relative', width: '100%', borderRadius: '12px', overflow: 'hidden', background: '#0a0e14' }}>
          <img src="/worldmap.png" alt="" style={{ width: '100%', display: 'block', opacity: 0.25 }} />
          {mapDots.map(function (dot, i) {
            var POS: Record<string, [number, number]> = {
              'America/Los_Angeles': [14, 37], 'America/New_York': [22, 34], 'America/Chicago': [20, 34], 'America/Denver': [17, 35], 'America/Toronto': [22, 32], 'America/Vancouver': [13, 30],
              'America/Sao_Paulo': [30, 65], 'America/Mexico_City': [16, 43], 'America/Buenos_Aires': [28, 73], 'America/Bogota': [20, 49],
              'Europe/London': [47, 27], 'Europe/Paris': [48, 28], 'Europe/Berlin': [50, 27], 'Europe/Madrid': [47, 31], 'Europe/Rome': [50, 30], 'Europe/Amsterdam': [49, 26], 'Europe/Stockholm': [51, 22], 'Europe/Dublin': [46, 26], 'Europe/Lisbon': [45, 32], 'Europe/Warsaw': [52, 26],
              'Asia/Tokyo': [83, 33], 'Asia/Shanghai': [78, 35], 'Asia/Singapore': [76, 51], 'Asia/Dubai': [61, 39], 'Asia/Kolkata': [68, 40], 'Asia/Seoul': [82, 33], 'Asia/Hong_Kong': [78, 38], 'Asia/Bangkok': [75, 44], 'Asia/Jakarta': [77, 53],
              'Australia/Sydney': [86, 74], 'Australia/Melbourne': [85, 76], 'Pacific/Auckland': [93, 75],
              'Africa/Johannesburg': [54, 67], 'Africa/Lagos': [49, 49], 'Africa/Cairo': [55, 36], 'Africa/Nairobi': [58, 51],
            }
            var pos = POS[dot.tz]
            if (!pos) return null
            var r = Math.min(14, 5 + dot.count * 2)
            return (<div key={i} style={{ position: 'absolute', left: pos[0] + '%', top: pos[1] + '%', transform: 'translate(-50%, -50%)', display: 'flex', flexDirection: 'column', alignItems: 'center', pointerEvents: 'none' }}>
              <span style={{ fontSize: '11px', fontWeight: 800, color: '#e0e4e8', marginBottom: '2px' }}>{dot.count}</span>
              <div style={{ width: r * 2 + 'px', height: r * 2 + 'px', borderRadius: '50%', background: GREEN, opacity: 0.5, boxShadow: '0 0 ' + (r * 2) + 'px ' + GREEN + '40, 0 0 ' + (r * 4) + 'px ' + GREEN + '15', position: 'relative', display: 'flex', alignItems: 'center', justifyContent: 'center' }}><div style={{ width: '5px', height: '5px', borderRadius: '50%', background: '#fff', opacity: 0.8 }} /></div>
              <span style={{ fontSize: '8px', fontWeight: 600, color: PLAT_DIM, marginTop: '2px', whiteSpace: 'nowrap' }}>{(dot.tz.split('/')[1] || dot.tz).replace('_', ' ')}</span>
            </div>)
          })}
        </div>)}</div>)}
        <SectionHeader title="Leaderboards" />
        <div className="ag2">
          <div style={{ background: CARD_BG, border: '1px solid ' + CARD_BORDER, borderRadius: '16px', padding: '18px', animation: 'analyticsCardIn 0.4s ease-out 0.3s both' }}><div style={{ fontSize: '15px', fontWeight: 700, color: '#e0e4e8', marginBottom: '18px' }}>Top Categories</div>{(data?.topCategories || []).map(function (cat: any, i: number) { var maxCount = data.topCategories[0]?.count || 1; var barColor = i === 0 ? GREEN : i < 3 ? BLUE : PLAT_DIM; return (<div key={i} style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '10px' }}><span style={{ fontSize: '12px', color: PLAT_DARK, width: '20px', textAlign: 'right', fontWeight: 700 }}>{i + 1}</span><span style={{ fontSize: '13px', color: '#e0e4e8', fontWeight: 600, width: '130px', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{fmtCat(cat.category)}</span><div style={{ flex: 1, height: '8px', borderRadius: '4px', background: 'rgba(255,255,255,0.04)' }}><div style={{ height: '100%', borderRadius: '4px', background: barColor, width: (cat.count / maxCount * 100) + '%' }} /></div><span style={{ fontSize: '12px', color: '#e0e4e8', fontWeight: 700, width: '32px', textAlign: 'right' }}>{cat.count}</span></div>) })}</div>
          <div style={{ background: CARD_BG, border: '1px solid ' + CARD_BORDER, borderRadius: '16px', padding: '18px', animation: 'analyticsCardIn 0.4s ease-out 0.35s both' }}><div style={{ fontSize: '15px', fontWeight: 700, color: '#e0e4e8', marginBottom: '18px' }}>Top Users</div>{(data?.topUsers || []).slice(0, 8).map(function (u: any, i: number) { return (<div key={i} style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '10px', padding: '8px 10px', borderRadius: '10px', background: i === 0 ? 'rgba(212,175,55,0.08)' : 'transparent', border: i === 0 ? '1px solid rgba(212,175,55,0.2)' : '1px solid transparent' }}><span style={{ fontSize: '12px', color: i === 0 ? GOLD : PLAT_DARK, fontWeight: 700, width: '20px', textAlign: 'right' }}>{i + 1}</span><span style={{ fontSize: '13px', color: '#e0e4e8', fontWeight: 600, flex: 1, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{u.session_id.slice(0, 8)}...</span><span style={{ fontSize: '11px', color: PLAT_DIM, fontWeight: 700 }}>{u.rank}</span><span style={{ fontSize: '13px', color: '#e0e4e8', fontWeight: 700, width: '65px', textAlign: 'right' }}>{fmtNum(u.total_points)}</span><span style={{ fontSize: '12px', color: GOLD, fontWeight: 700, width: '45px', textAlign: 'right' }}>{u.gold_coins}</span></div>) })}<div style={{ marginTop: '18px', paddingTop: '14px', borderTop: '1px solid rgba(255,255,255,0.05)' }}><div style={{ fontSize: '12px', fontWeight: 700, color: PLAT_DIM, letterSpacing: '1px', textTransform: 'uppercase', marginBottom: '10px' }}>Top Streaks</div>{(data?.streakLeaders || []).map(function (s: any, i: number) { return (<div key={i} style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '6px' }}><span style={{ fontSize: '16px' }}>&#128293;</span><span style={{ fontSize: '13px', color: '#e0e4e8', fontWeight: 600, flex: 1 }}>{s.session_id.slice(0, 8)}...</span><span style={{ fontSize: '14px', color: AMBER, fontWeight: 800 }}>{s.current_streak} days</span></div>) })}</div></div>
        </div>
        <SectionHeader title="Activity Heatmap" />
        <div style={{ background: CARD_BG, border: '1px solid ' + CARD_BORDER, borderRadius: '16px', padding: '18px', animation: 'analyticsCardIn 0.4s ease-out 0.4s both', overflowX: 'auto' }}><div style={{ display: 'flex', flexWrap: 'wrap', gap: '3px', maxWidth: '700px' }}>{heatmapGrid.map(function (cell, i) { var alpha = cell.intensity === 0 ? 0.04 : 0.12 + cell.intensity * 0.7; var cellColor = cell.intensity > 0.6 ? GREEN : cell.intensity > 0.3 ? BLUE : 'rgba(168,178,189,' + alpha + ')'; return <div key={i} title={cell.date + ': ' + cell.count} style={{ width: '11px', height: '11px', borderRadius: '2px', background: cell.intensity > 0.3 ? cellColor : 'rgba(168,178,189,' + alpha + ')', opacity: cell.intensity > 0.3 ? 0.8 : 1 }} /> })}</div><div style={{ display: 'flex', alignItems: 'center', gap: '5px', marginTop: '12px', fontSize: '11px', fontWeight: 600, color: PLAT_DARK }}><span>Less</span>{[0.04, 0.2, 0.4].map(function (a, i) { return <div key={i} style={{ width: '11px', height: '11px', borderRadius: '2px', background: 'rgba(168,178,189,' + a + ')' }} /> })}<div style={{ width: '11px', height: '11px', borderRadius: '2px', background: BLUE, opacity: 0.8 }} /><div style={{ width: '11px', height: '11px', borderRadius: '2px', background: GREEN, opacity: 0.8 }} /><span>More</span></div></div>
        <SectionHeader title="Recent Activity" />
        <div style={{ background: CARD_BG, border: '1px solid ' + CARD_BORDER, borderRadius: '16px', padding: '18px 24px', animation: 'analyticsCardIn 0.4s ease-out 0.5s both', maxHeight: '240px', overflowY: 'auto' }}>{(data?.sparkEconomy || []).slice(-25).reverse().map(function (entry: any, i: number) { var time = new Date(entry.created_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }); var reason = entry.reason.replace(/_/g, ' '); return (<div key={i} style={{ display: 'flex', alignItems: 'center', gap: '10px', padding: '5px 0', borderBottom: i < 24 ? '1px solid rgba(255,255,255,0.03)' : 'none', fontSize: '13px' }}><span style={{ color: PLAT_DIM, width: '50px', flexShrink: 0, fontWeight: 600 }}>{time}</span><span style={{ color: '#e0e4e8', flex: 1, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', fontWeight: 500 }}>{reason}</span><span style={{ color: entry.amount > 0 ? GREEN : RED, fontWeight: 700, width: '45px', textAlign: 'right' }}>{entry.amount > 0 ? '+' : ''}{entry.amount}</span></div>) })}</div>
        <div style={{ textAlign: 'center', marginTop: '40px', paddingBottom: '20px' }}><a href="/admin" style={{ fontSize: '13px', color: PLAT_DIM, textDecoration: 'none', fontWeight: 600 }}>&#8592; Back to Admin</a></div>
      </div>
    </div>
  )
}
